default:

  components: "views/shared/javascripts/v2/vendor/"
  payload: "views/shared/javascripts/v2/payloads/"

  apps:
    neatline: "views/shared/javascripts/v2/applications/neatline/"
    editor: "views/shared/javascripts/v2/applications/editor/"

  vendor:
    jquery: "jquery/jquery.js"
    underscore: "underscore/underscore.js"
    backbone: "backbone/backbone.js"
    marionette: "backbone/marionette.js"
    d3: "d3/d3.js"
