default:

  app:                  views/shared/javascripts/app/
  vendor:               views/shared/javascripts/components/

  js:
    payload:            views/shared/javascripts/shared/payloads/
    lib:
      jquery:           jquery/jquery.js
      underscore:       underscore/underscore.js
      underscore_s:     underscore.string/lib/underscore.string.js
      backbone:         backbone/backbone.js
      eventbinder:      Backbone.EventBinder/lib/backbone.eventbinder.js
      wreqr:            Backbone.Wreqr/lib/backbone.wreqr.js
      marionette:       backbone.marionette/lib/backbone.marionette.js
      openlayers:       openlayers/build/OpenLayers.js
      bootstrap:        bootstrap/bootstrap/js/bootstrap.js
      d3:               d3/d3.v2.js

  css:
    payload:            views/shared/css/payloads/
    lib:
      bootstrap:        bootstrap/bootstrap/css/bootstrap.min.css
      openlayers:       openlayers/theme/default/style.css

    stylus:
      source:           views/shared/css/stylus/
      mappings:
        neatline.styl:  neatline.css
        editor.styl:    editor.css
        overrides.styl: overrides.css
